### ISSUE TITLE
configure and run a micro store service when starting ocis

### ISSUE THREAD

**Issue by butonic** [owncloud/product#113]
services like ocis-accounts and ocis-settings currently store data in the filesystem. We should switch to the micro store interface, which is a kv store interface that also allows indexing metadata and can be implemented with a file (boltdb) based implementation, etcd or redis (quarkdb) ... 

- [ ] start a micro store service when running ocis
- [ ] make ocis-ocs use it to store the users signingkey
- [ ] make ocis-accounts use the store. It should be able to get rid of bleve.
- [ ] make ocis-settings use the store

Upstream design documentd for store: https://github.com/micro/development/blob/master/design/framework/store.md

related: https://github.com/owncloud/ocis/issues/95

**Comment by PVince81** [comment]
when you say "use the store" does it mean "one store microservice for all" or does each have their own instance of such store with separate data, specific to the using service ?

a diagram might help

**Comment by butonic** [comment]
That is up to the deployment. A single service would as it allows seperating keys into databases and tables. For scaling purposes it might make sense to deploy up multiple instances. For HA / Redundance it will become a requirement. But for those scenarios the implmentation should be changed / extended / redesigned as well.
