### ISSUE TITLE
Failing Phoenix WebUI Test related to public links

### ISSUE THREAD

**Issue by refs** [owncloud/product#161]
Failing Build: https://cloud.drone.io/owncloud/ocis/1177/8/7
Failing Scenario: `tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature:49`

We're unaware of what made this test fail but it should be reproducible, and fixed.

### Tasks

- [x] fix env: https://github.com/owncloud/ocis/pull/465
- [x] also add to docker-compose in ocis repo: https://github.com/owncloud/ocis/pull/469#issuecomment-677478288
- [x] reenable the failing test: https://github.com/owncloud/phoenix/pull/3965
- [x] update commit id https://github.com/owncloud/ocis/pull/471

**Comment by PVince81** [comment]
Confirmed, I was able to reproduce this issue.

Strange that basic auth would not affect the shares

**Comment by PVince81** [comment]
the two shares exist in the file but have a different IDP:
```
{
  "dvqdjSCjSxStNfe": {
    "password": "",
    "share": "{\"id\":{\"opaqueId\":\"dvqdjSCjSxStNfe\"},\"token\":\"VsIUUtoCJCRkxIO\",\"resourceId\":{\"storageId\":\"1284d238-aa92-42ce-bdc4-0b0000009154\",\"opaqueId\":\"3269a0fa-65c1-45ee-acad-d4494f7cfc57\"},\"permissions\":{\"permissions\":{\"getPath\":true,\"getQuota\":true,\"initiateFileDownload\":true,\"listGrants\":true,\"listContainer\":true,\"listFileVersions\":true,\"listRecycle\":true,\"stat\":true}},\"owner\":{\"idp\":\"https://ocis-server:9200\",\"opaqueId\":\"4c510ada-c86b-4815-8820-42cdf82c3d51\"},\"creator\":{\"idp\":\"https://ocis-server:9200\",\"opaqueId\":\"4c510ada-c86b-4815-8820-42cdf82c3d51\"},\"ctime\":{\"seconds\":\"1597845515\",\"nanos\":126623393},\"mtime\":{\"seconds\":\"1597845515\",\"nanos\":126623393},\"expiration\":{\"seconds\":\"1597874399\",\"nanos\":999000000},\"displayName\":\"Quick action link\"}"
  },
  "oiWmdzFxPLFmlKB": {
    "password": "",
    "share": "{\"id\":{\"opaqueId\":\"oiWmdzFxPLFmlKB\"},\"token\":\"GrXsJkofrTeGssx\",\"resourceId\":{\"storageId\":\"1284d238-aa92-42ce-bdc4-0b0000009154\",\"opaqueId\":\"3269a0fa-65c1-45ee-acad-d4494f7cfc57\"},\"permissions\":{\"permissions\":{\"getPath\":true,\"getQuota\":true,\"initiateFileDownload\":true,\"listGrants\":true,\"listContainer\":true,\"listFileVersions\":true,\"listRecycle\":true,\"stat\":true}},\"owner\":{\"idp\":\"https://localhost:9200\",\"opaqueId\":\"4c510ada-c86b-4815-8820-42cdf82c3d51\"},\"creator\":{\"idp\":\"https://localhost:9200\",\"opaqueId\":\"4c510ada-c86b-4815-8820-42cdf82c3d51\"},\"ctime\":{\"seconds\":\"1597845599\",\"nanos\":125758774},\"mtime\":{\"seconds\":\"1597845599\",\"nanos\":125758774}}"
  }
}
```
the second one is the one created with basic auth.

so it is likely that shares get filtered out when the IDP is different.

or maybe the basic auth is leading to a different user id with a different IDP than the given domain.

@butonic does that ring any bells ? I guess a lot could go wrong here with tests

**Comment by PVince81** [comment]
I've found this in the log for the last curl request using basic auth:
```
2020-08-19T16:05:42+02:00 DBG Bind success binddn=cn=einstein,ou=users,dc=example,dc=org service=glauth src={"IP":"127.0.0.1","Port":44860,"Zone":""}
2020-08-19T16:05:42+02:00 DBG authenticated user entry={"Attributes":[{"ByteValues":["ZWluc3RlaW4="],"Name":"cn","Values":["einstein"]},{"ByteValues":["NGM1MTBhZGEtYzg2Yi00ODE1LTg4MjAtNDJjZGY4MmMzZDUx"],"Name":"ownCloudUUID","Values":["4c510ada-c86b-4815-8820-42cdf82c3d51"]},{"ByteValues":["QWxiZXJ0IEVpbnN0ZWlu"],"Name":"displayName","Values":["Albert Einstein"]},{"ByteValues":["ZWluc3RlaW5AZXhhbXBsZS5vcmc="],"Name":"mail","Values":["einstein@example.org"]}],"DN":"cn=einstein,ou=users,dc=example,dc=org"} pkg=rgrpc service=reva traceid=2eee2ba50188cd0a68bbd8be48f0ead7 user={"display_name":"Albert Einstein","id":{"idp":"https://localhost:9200","opaque_id":"4c510ada-c86b-4815-8820-42cdf82c3d51"},"mail":"einstein@example.org","username":"einstein"}
2020-08-19T16:05:42+02:00 INF user id:<idp:"https://localhost:9200" opaque_id:"4c510ada-c86b-4815-8820-42cdf82c3d51" > username:"einstein" mail:"einstein@example.org" display_name:"Albert Einstein"  authenticated pkg=rgrpc service=reva traceid=2eee2ba50188cd0a68bbd8be48f0ead7
```

not sure where that localhost comes from, I wonder if there's another env var that needs to be set to make this right

**Comment by PVince81** [comment]
the message comes from Reva after searching for the user in LDAP: https://github.com/cs3org/reva/blob/master/pkg/auth/manager/ldap/ldap.go#L186

this points at some config in the auth manager, so we're likely missing an env var

**Comment by PVince81** [comment]
adding this solves the issue when testing manually:
```
REVA_LDAP_IDP=https://ocis-server:9200
```

@individual-it can you adjust it in whatever environment the original issue occurred ?

**Comment by PVince81** [comment]
PR here for fixing the config: https://github.com/owncloud/ocis/pull/465

**Comment by PVince81** [comment]
should we also adjust the ocis-reva and other repos ? it seems the env variables are different there @individual-it

**Comment by PVince81** [comment]
update commit id: https://github.com/owncloud/ocis/pull/471

**Comment by individual-it** [comment]
> should we also adjust the ocis-reva and other repos ? it seems the env variables are different there @individual-it

yes we should, those settings keep on changing, hard to keep up

**Comment by individual-it** [comment]
@PVince81 are you on this, or should we take over for the other repos?

**Comment by individual-it** [comment]
actually its fixed in phoenix https://github.com/owncloud/phoenix/pull/3985/files#diff-74dc60589e0610c07e491b31f8693b2bR1177
and ocis-reva does not run phoenix tests, so I guess we can close this
