### ISSUE TITLE
Settings service

### ISSUE THREAD

**Issue by micbar** [owncloud/product#17]
## Concept

- Outcome of concepting workshop in https://github.com/owncloud/ocis/pull/171
- Ticket for Phoenix implementation https://github.com/owncloud/enterprise/issues/3899

## Tasks

- Create a new service
  - [x] Repo setup
  - [x] Update Boilerplate https://github.com/owncloud/boilr-ocis-extension/pull/10
  - [x] Run Boilerplate
  - [ ] protobuf spec for...
    - [x] registering and listing settings bundles
    - [x] loading and saving settings of a user
    - [ ] registering roles and permissions (along with settings bundles) https://github.com/owncloud/ocis-settings/issues/10
  - [ ] grpc services for...
    - [x] registering and listing settings bundles
    - [x] loading and saving settings of a user
    - [ ] registering roles and permissions (along with settings bundles) https://github.com/owncloud/ocis-settings/issues/10
    - [ ] getting and setting roles of a user https://github.com/owncloud/ocis-settings/issues/10
    - [ ] when roles and permissions exist: filter settings in settings bundles to only deliver the settings the user is allowed to see https://github.com/owncloud/ocis-settings/issues/10
  - [x] http services for...
    - [x] delivering the web frontend for integration in phoenix
    - [x] setup swagger http endpoint generation from protobuf => only requires annotations on grpc services to generate http endpoints and a working javascript client
    - [x] fix that generated web endpoints try to decode the request body for get requests
  - [x] use `X-Ocis-Accounts-Uuid` from request header to exchange `me` account uuid keyword with the actual account uuid of the authenticated user. https://github.com/owncloud/ocis-settings/issues/12

- Use the accounts service as a first consumer of the settings service
    - [x] for quick result: hardcode settings bundle registration
    - [x] fix that the account service doesn't die anymore on init if the settings service is not reachable (only show a warning instead)
    - ~~possible improvement: put user profile settings bundle content into a (json) file, which then gets loaded from disc -> hardcoded settings bundles kind of cluttering the code~~
    - [x] use service discovery for reaching settings service instead of hardcoded address
    - [x] provide endpoint for getting a uuid for the authenticated user (required for loading and saving settings, keyed by user uuid)

- Use phoenix as an early consumer of the settings service
    - [x] bring settings values into phoenix through owncloud-sdk
    - [x] use language from profile settings bundle in phoenix
    - [ ] use timezone from profile settings bundle in phoenix https://github.com/owncloud/phoenix/issues/3496

- Create UI POC: settings
    - [x] set up empty ocis-web-app for integration in ocis-web: export appInfo, navItems, routes 
    - [x] integrate generated js client for backend communication
    - [x] implement generating and rendering all form elements from the settings bundle content
      - [x] string -> text field
      - [x] int -> number input
      - [x] bool -> checkbox
      - [x] single choice list -> dropdown with radio buttons
      - [x] multi choice list -> dropdown with checkboxes
    - [x] navigation between settings bundles of different extensions through router
    - [x] generate sidebar nav items from existing settings bundles for navigating between settings of different extensions https://github.com/owncloud/phoenix/issues/3497
    - [x] implement loading and saving user settings for form elements
    - [ ] fix and then use radio button in ODS https://github.com/owncloud/owncloud-design-system/issues/726
    - [ ] fix and then use checkbox in ODS https://github.com/owncloud/owncloud-design-system/issues/728
    - [x] fix keyboard event handlers on oc-text-input component in ODS https://github.com/owncloud/owncloud-design-system/issues/745

- Create UI POC: assigning roles to users?

- Documentation
  - [ ] settings extension
    - [x] abstract concept, including diagram
    - [x] settings bundle description
    - [x] settings value description https://github.com/owncloud/ocis-settings/issues/11
    - [x] glossary (extend step by step)
    - [ ] roles & permissions concept https://github.com/owncloud/ocis-settings/issues/13
  - [ ] howto: registering settings bundles with the settings service https://github.com/owncloud/ocis-hello/issues/71

- Concept work
    - [x] First settings: Language and Timezone for the user profile settings bundle.
    - [ ] Open question: Required to Define useful settings for other services? https://github.com/owncloud/ocis/issues/289

- Tests
    - [ ] Acceptance test in phoenix for changing language https://github.com/owncloud/phoenix/issues/3491
    - [x] GRPC tests in ocis-settings https://github.com/owncloud/ocis-settings/pull/2

## User stories for POC

- As a user new to the instance I want that oCIS remembers me if I log in a second time to enable other users to share with me.
- As a user on oCIS I want to set my timezone the UI to have correct values in my web VIEW when I am traveling.

## Estimation

Effort: L
Complexity: L...

**Comment by micbar** [comment]
@kulmann Repo is ready too push the boilerplate

**Comment by kulmann** [comment]
boilerplate pushed 👍

**Comment by refs** [comment]
@kulmann Perhaps change the copy on the cancel button to English for consistency?

**Comment by kulmann** [comment]
> @kulmann Perhaps change the copy on the cancel button to English for consistency?

Nope, automatically translated by phoenix already. ;-)

**Comment by kulmann** [comment]
Loading and saving user settings values now works in the UI. This still needs visual improvements in the frontend and currently has a hardcoded account uuid in the service (need to pick it from the request header), but is a big step forward.

The values in the screenshot have been saved through the form and are there again after a page reload.
![Screenshot 2020-05-07 at 18 04 14](https://user-images.githubusercontent.com/3532843/81317722-7cfd8780-908d-11ea-8008-c8350d8034cd.png)

Persisted JSON looks like this:
![Screenshot 2020-05-07 at 18 04 44](https://user-images.githubusercontent.com/3532843/81317830-a4eceb00-908d-11ea-94e5-61a8304dae24.png)

cc @refs @micbar @felixboehm @pmaier1

**Comment by micbar** [comment]
closed
