### ISSUE TITLE
[deployment] Add more deployment scenarios

### ISSUE THREAD

**Issue by micbar** [owncloud/product#18]
## Scenarios

- [ ] docker-compose file WIP in https://github.com/owncloud-docker/compose-playground/pull/16
- [ ] Example: oCIS with eos via docker-compose @felixboehm  
- [ ] Example: oCIS with Keycloak (Benedikt, MStingl)
- [ ] Example: oCIS with Ping
- [ ] Example: oCIS with BigIP F5 (Erik?)
- [ ] Example: oc10 SAML and oCIS OIDC using simple-saml
- [ ] Example: oc10 CAS and oCIS OIDC using IDP: ?
- [ ] Example: oc10 Kerberos and oCIS OIDC using IDP: ?
- [ ] Repo with K8 helm charts: https://github.com/owncloud/charts
- [ ] Example: Minikube with K8 Service Discovery https://kubernetes.io/docs/setup/learning-environment/minikube/#minikube-features
- [ ] Are there managed K8 platforms where we can setup and test?
- [ ] Basic Remote oCIS: https://owncloud.github.io/ocis/basic-remote-setup/ ✓
- [ ] Example: oCIS on Hetzner with cloudflare domain
- [ ] Example: Treafik, oCIS on Hetzner
- [ ] Example: Prometheus and Jager with oCIS - compose snippets? https://github.com/owncloud/product/issues/35
- [ ] Example: oc10 with Phoenix (and treafik) on Hetzner
- [ ] Client development / QA: oCIS from branches with Domain / Traefik. @MBarz docs
- [ ] Do Research on connecting a productive LDAP Server
   - [ ] Configure it in the demo system

## Research
- [ ] https://github.com/owncloud/ocis/issues/182

**Comment by felixboehm** [comment]
I'd like to have specific issues / user stories for deployment scenarios and replace this generic issue
