### ISSUE TITLE
[ocis][clients] Large File Uploads

### ISSUE THREAD

**Issue by micbar** [owncloud/product#19]
# Future

- Use TUS io protocol www.tus.io

## Use Cases

- Large File Uploads
- Instable connections
- middlewares are interfering

Nasty middleware example:
PUT > 100MB will fail:
https://demo.shniq.cloud/
Cloudflare limits upload size (HTTP POST request size) per plan type:
100MB Free and Pro
(Source: https://support.cloudflare.com/hc/en-us/articles/200172516#h_51422705-42d0-450d-8eb1-5321dcadb5bc)

## Cern

- Needs to be decided it CERN and Clients will stick to Chunking V1 and go directly to Tus (V3)

## oCIS

- [x] OC-DAV handler will forward tus requests
- [x] expose capabilities: https://github.com/owncloud/ocis-reva/issues/177

## Reva changes

- [x] https://github.com/cs3org/reva/pull/286
- [x] COPY regression with TUS: https://github.com/owncloud/ocis-reva/issues/173
- [x] preserve mtime: https://github.com/owncloud/ocis-reva/issues/174 (to discuss)
- [x] issue with creation-with-upload: https://github.com/cs3org/reva/issues/710

## Phoenix

- [x] basic TUS impl
- [ ] creation-with-upload support: https://github.com/owncloud/phoenix/pull/3436

### Start next sprint with TUS client https://github.com/owncloud/enterprise/issues/3901

- [x] Server Side Data Service
- [x] Oc-DAV Service
- [x] JS Client added to phoenix/sdk: https://github.com/owncloud/phoenix/issues/67
- [x] Implement the js client

Effort: M
Complexity: S/M

## Desktop

- Start with TUS for 2.8

## iOS

- TUS implementaition will start as soon as Phoenix POC is tested

## Android...

**Comment by micbar** [comment]
@michaelstingl @butonic @felixboehm

**Comment by PVince81** [comment]
We might want to clarify that the scope of this only applies to authenticated uploads, not public link nor file drop. In OC 10 we decided against chunking for anonymous access due to the possibility of spamming the upload cache with random chunks by unauthenticated users.

**Comment by PVince81** [comment]
Some tech info about the curl requests for a simple "two-request" based upload which can be useful for clients:

1. Curl for initiating an upload:
```
curl for an upload:
- initial POST to create a new upload (no payload):
```
curl -D - 'https://localhost:9200/remote.php/dav/files/einstein/' \
  -X 'POST' \
  -u einstein:relativity \
  -H 'Tus-Resumable: 1.0.0' \
  -H 'Upload-Length: 10000' \
  -H 'Upload-Metadata: filename bG1tcy0xLjIuMC1yYzgtbGludXgteDg2XzY0LkFwcEltYWdl,filetype YXBwbGljYXRpb24vdm5kLmFwcGltYWdl,size OTgxNjg1MjA=,mtime MTU1MjIzOTI1MC4wNDg=' \
  --insecure
HTTP/1.1 201 Created
Access-Control-Allow-Headers: Tus-Resumable, Upload-Length, Upload-Metadata, If-Match
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Tus-Resumable, Location
Content-Length: 0
Date: Mon, 27 Apr 2020 13:52:17 GMT
Location: http://localhost:9164/data/3b0ba66e-4745-437e-9410-6d9a7ee06eee
Tus-Resumable: 1.0.0
Vary: Origin
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNTg3OTk5MTM3LCJpYXQiOjE1ODc5OTU1MzcsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjkyMDAiLCJ1c2VyIjp7ImlkIjp7ImlkcCI6Imh0dHBzOi8vbG9jYWxob3N0OjkyMDAiLCJvcGFxdWVfaWQiOiJlaW5zdGVpbiJ9LCJ1c2VybmFtZSI6ImVpbnN0ZWluIiwibWFpbCI6ImVpbnN0ZWluQGV4YW1wbGUub3JnIiwiZGlzcGxheV9uYW1lIjoiRWluc3RlaW4ifX0.etJPHNQHXOJnZY88b3ZL7HZ55_PhXvKBA6Lm2tjS-LY
```
=> you can replace username/password with an authorization + bearer token instead

2. Then send the data there to the location got in the "Location" header:
```
curl -D - -k 'http://localhost:9164/data/3b0ba66e-4745-437e-9410-6d9a7ee06eee' \
  -X 'PATCH' \
  -u einstein:relativity \
  -H 'Connection: keep-alive' \
  -H 'Tus-Resumable: 1.0.0' \
  -H 'Upload-Offset: 0' \
  -H 'Content-Type: application/offset+octet-stream' \
  -d "abcdefghijklmno"  
HTTP/1.1 204 No Content
Tus-Resumable: 1.0.0
Upload-Offset: 15
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNTg3OTk5NjIxLCJpYXQiOjE1ODc5OTYwMjEsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjkyMDAiLCJ1c2VyIjp7ImlkIjp7ImlkcCI6Imh0dHBzOi8vbG9jYWxob3N0OjkyMDAiLCJvcGFxdWVfaWQiOiJlaW5zdGVpbiJ9LCJ1c2VybmFtZSI6ImVpbnN0ZWluIiwibWFpbCI6ImVpbnN0ZWluQGV4YW1wbGUub3JnIiwiZGlzcGxheV9uYW1lIjoiRWluc3RlaW4ifX0.ES-3q4Cf1tEbF_umOIzzXbLcLujeAHHo4bkUtI6PwAg
X-Content-Type-Options: nosniff
Date: Mon, 27 Apr 2020 14:00:21 GMT
```
Since we only uploaded a few bytes, the offset moved to 15

Replace "abcdefghijklmno" with the file data. (I didn't manage to and `-F` uses multipart which mangles the content-type)

**Comment by PVince81** [comment]
I've updated the checkboxes and added a few more as I continue finding small issues

**Comment by PVince81** [comment]
Matching Jira ticket https://jira.owncloud.com/browse/OCIS-9 was closed.
