### ISSUE TITLE
make all ocs  and webdav API tests pass

### ISSUE THREAD

**Issue by micbar** [owncloud/product#27]
# make all ocs  and webdav API tests pass

Guide to work with the testsuite in DEV docs.

https://owncloud.github.io/extensions/ocis_reva/testing/

## Tasks
I've grepped the current tests on core master (as of commit 1bec7a397faa37f2edda6af35d2342e433499cf2), came up with the following existing issues:

### General

- [ ] missing XML body for error responses, should we make them like Sabre DAV ??
   - [ ] [MKCOL on existing resource](https://github.com/owncloud/ocis-reva/issues/168)
   - [ ] [PROPFIND on non-existing resource](https://github.com/owncloud/ocis-reva/issues/163)
   - [ ] [HTTP 401 Unauthorized responses don't contain a body](https://github.com/owncloud/ocis-reva/issues/30)
- [ ] missing skeleton folder creation (required by many tests): https://github.com/owncloud/ocis-reva/issues/167

### File management

- [x] [PROPFIND does not return file size in drone](https://github.com/owncloud/ocis-reva/issues/67)
- [ ] [no OC-Checksum header when downloading file](https://github.com/owncloud/ocis-reva/issues/98)
- [ ] [OC-Checksum header not checked when uploading file](https://github.com/owncloud/ocis-reva/issues/99)
- [x] [versions survive the deletion of a file](https://github.com/owncloud/ocis-reva/issues/94)
- [ ] [Range Header is not obeyed when downloading a file](https://github.com/owncloud/ocis-reva/issues/12)
- [x] ~~[server returns 500 when trying to access a not existing file](https://github.com/owncloud/ocis-reva/issues/13)~~ => https://github.com/owncloud/ocis-reva/issues/163
- [ ] [renaming a resource does not work](https://github.com/owncloud/ocis-reva/issues/14)
   - [x] fix
   - [ ] enable tests
- [ ] [blacklisted filenames like .htaccess & file.parts can be uploaded](https://github.com/owncloud/ocis-reva/issues/15)
- [ ] litmus tests fail:
   - [x] [shallow COPY (Depth: 0)](https://github.com/owncloud/ocis-reva/issues/171)
   - [x] [recursive COPY (Depth: infinity)](https://github.com/owncloud/ocis-reva/issues/173)
   - [ ] [MOVE](https://github.com/owncloud/ocis-reva/issues/182)
   - [ ] custom properties:
      - [x] [PROPFIND does not return custom file properties](https://github.com/owncloud/ocis-reva/issues/57)
      - [ ] [wrong propstat code for removed properties](https://github.com/owncloud/ocis-reva/issues/186)
      - [ ] [props failures](https://github.com/owncloud/ocis-reva/issues/183)
   - [ ] [missing/broken LOCK support](https://github.com/owncloud/ocis-reva/issues/172)
   - [x] [cleanup issues](https://github.com/owncloud/ocis-reva/issues/184)
- [ ] [in core webDav API tests adjust scenarios where w direct WebDAV URL is given](https://github.com/owncloud/ocis-reva/issues/36)
   - [x] fix
   - [ ] enable test
- [ ] [REPORT request not implemented](https://github.com/owncloud/ocis-reva/issues/39)
- [ ] [cannot get ocs:share-permissions via WebDAV](https://github.com/owncloud/ocis-reva/issues/47)
- [ ] [deleted files come and go in the trashbin listing](https://github.com/owncloud/ocis-reva/issues/52)
- [ ] [uploading with old-chunking does not work](https://github.com/owncloud/ocis-reva/issues/17) => deferred / obsoleted by TUS ?
- [ ] [chunking v2 endpoint](https://github.com/owncloud/ocis-reva/issues/56) => deferred / obsoleted by TUS ?
- [x] [creating a folder that already exists returns HTTP 405 Method Not Allowed](https://github.com/owncloud/ocis-reva/issues/165)

### Sharing

- [ ] [sharing fails with `error searching recipient`](https://github.com/owncloud/ocis-reva/issues/64)
- [ ] [listing received shares does not work](https://github.com/owncloud/ocis-reva/issues/11)
- [ ] [share_with field in response after sharing has an extra @localhost attached to the username](https://github.com/owncloud/ocis-reva/issues/20)
- [ ] [retrieving information about shares via ocs API is not possible](https://github.com/owncloud/ocis-reva/issues/21)
- [ ] [ocs v2 endpoint still returns ocs v1 status codes](https://github.com/owncloud/ocis-reva/issues/26)
- [ ] [remote shares API endpoint does not exist](https://github.com/owncloud/ocis-reva/issues/31)
- [ ] [no way to set default folder for received shares](https://github.com/owncloud/ocis-reva/issues/42)
- [ ] [multiple values missing in response when sharing file](https://github.com/owncloud/ocis-reva/issues/43)
- [ ] [create & delete permissions are applied to files when shared](https://github.com/owncloud/ocis-reva/issues/44)
- [ ] [a share with invalid permissions can be created](https://github.com/owncloud/ocis-reva/issues/45)
- [ ] [when sharing a folder to a user the default permissions are "1"](https://github.com/owncloud/ocis-reva/issues/46)
- [ ] [public webdav API endpoint does not exist](https://github.com/owncloud/ocis-reva/issues/49)

### Settings

- [ ] [not possible to set quota for users](https://github.com/owncloud/ocis-reva/issues/101)
- [ ] [ocs config enpoint only accesible by authorized users](https://github.com/owncloud/ocis-reva/issues/29)
- [ ] [files_external mounts endpoint does not exist](https://github.com/owncloud/ocis-reva/issues/32)
- [ ] [various sharing settings cannot be set](https://github.com/owncloud/ocis-reva/issues/41)
- [ ] [system configuration options missing](https://github.com/owncloud/ocis-reva/issues/54)
- [ ] [There is no such thing like a "super-user"](https://github.com/owncloud/ocis-reva/issues/65)
- [ ] [no command equivalent to occ](https://github.com/owncloud/ocis-reva/issues/97)

### User Management

- [ ] [groups endpoint does not exists](https://github.com/owncloud/ocis-reva/issues/34)

### Other APIs

- [ ] [ocs apps endpoint does not exist ](https://github.com/owncloud/ocis-reva/issues/33)
- [ ] [ocs privatedata endpoint does not exist](https://github.com/owncloud/ocis-reva/issues/35)
- [ ] [Collaborative Tag management](https://github.com/owncloud/ocis-reva/issues/51)
- [x] [PROPFIND on the root of the /webdav enpoints returns ERROR 500](https://github.com/owncloud/ocis-reva/issues/62)
- [ ] [comments API](https://github.com/owncloud/ocis-reva/issues/38)

### Security

- [ ] :warning: [users can access each-others data using the new webdav API](https://github.com/owncloud/ocis-reva/issues/9)
- [ ] [security headers not served when downloading a file](https://github.com/owncloud/ocis-reva/issues/66)
- [ ] [no way to enforce token auth](https://github.com/owncloud/ocis-reva/issues/37)
- [ ] [no robots.txt available](https://github.com/owncloud/ocis-reva/issues/100)
- [ ] [wildcard Access-Control-Allow-Origin](https://github.com/owncloud/ocis-reva/issues/27)
- [ ] [cannot generate token using /token/generate endpoint](https://github.com/owncloud/ocis-reva/issues/28)
- [ ] [app passwords are not possible](https://github.com/owncloud/ocis-reva/issues/60)

### Todos

- [ ] Sort out tagged test pointing at non-existing ticket: https://github.com/owncloud/ocis-webdav/issues/187 => issue not found but mentionned in 
- [ ] TODO: link all those tickets from the matching product feature tickets

:information_source: Grep command: `grep -rie "issue-ocis" tests/acceptance | sed 's/.*\(ocis-[^\s ]*\).*/\1/' | sort | uniq | sed 's%\(ocis-[^-]*\)-\(\d*\)%- [ ] https://github.com/owncloud/\1/issues/\2%'`

**Comment by micbar** [comment]
EE ticket https://github.com/owncloud/enterprise/issues/3989

**Comment by PVince81** [comment]
Approach:
- [ ] search for all `@skipOnOcis` tests in the core repo, uncomment and see what tests still fail
- [ ] raise tickets based on failing tests if not fixable quickly (or list as checkbox here)

**Comment by PVince81** [comment]
I've grepped the current tests on core master (as of commit 1bec7a397faa37f2edda6af35d2342e433499cf2), came up with the following existing issues:

- [ ] https://github.com/owncloud/ocis-reva/issues/100
- [ ] https://github.com/owncloud/ocis-reva/issues/101
- [ ] https://github.com/owncloud/ocis-reva/issues/11
- [ ] https://github.com/owncloud/ocis-reva/issues/12
- [ ] https://github.com/owncloud/ocis-reva/issues/13
- [ ] https://github.com/owncloud/ocis-reva/issues/14
- [ ] https://github.com/owncloud/ocis-reva/issues/15
- [ ] https://github.com/owncloud/ocis-reva/issues/17
- [ ] https://github.com/owncloud/ocis-reva/issues/18
- [ ] https://github.com/owncloud/ocis-reva/issues/20
- [ ] https://github.com/owncloud/ocis-reva/issues/21
- [ ] https://github.com/owncloud/ocis-reva/issues/26
- [ ] https://github.com/owncloud/ocis-reva/issues/27
- [ ] https://github.com/owncloud/ocis-reva/issues/28
- [ ] https://github.com/owncloud/ocis-reva/issues/29
- [ ] https://github.com/owncloud/ocis-reva/issues/30
- [ ] https://github.com/owncloud/ocis-reva/issues/31
- [ ] https://github.com/owncloud/ocis-reva/issues/32
- [ ] https://github.com/owncloud/ocis-reva/issues/33
- [ ] https://github.com/owncloud/ocis-reva/issues/34
- [ ] https://github.com/owncloud/ocis-reva/issues/35
- [ ] https://github.com/owncloud/ocis-reva/issues/36
- [ ] https://github.com/owncloud/ocis-reva/issues/37
- [ ] https://github.com/owncloud/ocis-reva/issues/39
- [ ] https://github.com/owncloud/ocis-reva/issues/41
- [ ] https://github.com/owncloud/ocis-reva/issues/42
- [ ] https://github.com/owncloud/ocis-reva/issues/43
- [ ] https://github.com/owncloud/ocis-reva/issues/44
- [ ] https://github.com/owncloud/ocis-reva/issues/45
- [ ] https://github.com/owncloud/ocis-reva/issues/46
- [ ] https://github.com/owncloud/ocis-reva/issues/47
- [ ] https://github.com/owncloud/ocis-reva/issues/49
- [ ] https://github.com/owncloud/ocis-reva/issues/51
- [ ] https://github.com/owncloud/ocis-reva/issues/52
- [ ] https://github.com/owncloud/ocis-reva/issues/54
- [ ] https://github.com/owncloud/ocis-reva/issues/56
- [ ] https://github.com/owncloud/ocis-reva/issues/57
- [ ] https://github.com/owncloud/ocis-reva/issues/60
- [ ] https://github.com/owncloud/ocis-reva/issues/62
- [ ] https://github.com/owncloud/ocis-reva/issues/64
- [ ] https://github.com/owncloud/ocis-reva/issues/65
- [ ] https://github.com/owncloud/ocis-reva/issues/66
- [ ] https://github.com/owncloud/ocis-reva/issues/67
- [ ] https://github.com/owncloud/ocis-reva/issues/9
- [ ] https://github.com/owncloud/ocis-reva/issues/94
- [ ] https://github.com/owncloud/ocis-reva/issues/97
- [ ] https://github.com/owncloud/ocis-reva/issues/98
- [ ] https://github.com/owncloud/ocis-reva/issues/99
- [ ] https://github.com/owncloud/ocis-webdav/issues/187

Grep command: `grep -rie "issue-ocis" tests/acceptance | sed 's/.*\(ocis-[^\s ]*\).*/\1/' | sort | uniq | sed 's%\(ocis-[^-]*\)-\(\d*\)%- [ ] https://github.com/owncloud/\1/issues/\2%'`

**Comment by PVince81** [comment]
It is likely that enabling tests will take longer than expected. The reason is that one disabled test might hide another failure. For example you might want to reenable a test related to a MOVE operation, but that test also tests checksums which is still not implemented. So you need to replace the issue number with another one after researching which other case is related.

This seems to be the case for example in https://github.com/owncloud/ocis-reva/issues/14: while the main case works, a lot of tests still fail after reenabling, due to various other reasons to investigate. This will increase the estimate for every ticket.

**Comment by individual-it** [comment]
not all tests marked with an issue are skipped, some are already fixed

**Comment by PVince81** [comment]
Right, thanks. I forgot to look closely at the `@skipOnOcis` because somehow my brain connects an issue tag with an implicit skip. Also it seems that I didn't realize that grep for issue tags was pointing me at UI tests instead of API tests.

I'll go through the tickets I touched last week and recheck if the API tests were affected or not.
We might be closer to completion then.

**Comment by C0rby** [comment]
What do we do about tests which are broken by the tus code?
For example updateShare.feature:35.

**Comment by individual-it** [comment]
@C0rby I cannot find that test in the core repo, that line is in the middle of a scenario. And the whole file is tagged `skipOnOcis`, so it should not be executed in ocis at all :confused:

**Comment by C0rby** [comment]
Oh you are right, I copied the wrong path... let me change the path above

**Comment by PVince81** [comment]
if that one has a ticket number, please add the ticket to the checkbox list in the top post.
if there's no ticket, please raise one.

it seems there are already a bunch of sharing related tickets, I didn't look into them yet

**Comment by PVince81** [comment]
Reorganized the order of tickets in https://etherpad.owncloud.com/p/ocis-api-tests and in https://github.com/orgs/owncloud/projects/181 and https://github.com/orgs/owncloud/projects/182

**Comment by PVince81** [comment]
closing this, we should use the projects now to track progress
