### ISSUE TITLE
[Desktop] WinVFS

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/product#3]
**Stories**

- [ ] New folders should have vfs support available by default (https://github.com/owncloud/client/issues/6932)
- [ ] Automatic dehydration of outdated unpinned files (https://github.com/owncloud/client/issues/7084)
- [ ] Immediate download of files upon requesting download via context menu (https://github.com/owncloud/client/issues/7130)
- [ ] https://github.com/owncloud/client/issues/7156
- [ ] https://github.com/owncloud/client/issues/7175
- [ ] https://github.com/owncloud/client/issues/7192
- [ ] Automatic dehydration of not used files (https://github.com/owncloud/client/issues/7402)
- [ ] Implement menu entries with native Win Explorer integration (https://github.com/owncloud/client/issues/7746)
- [ ] Display sharing status in status column (https://github.com/owncloud/client/issues/7747)...
