### ISSUE TITLE
ocis-accounts backend

### ISSUE THREAD

**Issue by butonic** [owncloud/product#73]
We need to use the ocis-accounts service as the user backend. It contains normal users and guest accounts that we want to make accessible using LDAP so that kopano can access them.

## Tasks
- [x] Create an architecture overview (maybe diagram) before starting to implement
  - https://github.com/owncloud/ocis/pull/229 - request flow sequence diagram
  - https://github.com/owncloud/ocis/pull/243 - login flow sequence diagram
  - [x] Review of the Concept

## ocis-glauth tasks @butonic  
- [ ] test ocis-glauth against ocis-graph @butonic 
  - [ ] allow basic auth in graph api to implement bind, similar to the hack in the graphapi oc10 app?
    - done in https://github.com/owncloud/ocis-graph/pull/30
- [ ] Skeleton Users need to display the `displayName` (currently surname)

## ocis-accounts Tasks
- [x] allow account lookup using properties using email, displayname, username & password (in addition to uuid and sub) https://github.com/owncloud/ocis-accounts/pull/28
- [ ] current lookup implemented in https://github.com/owncloud/ocis-accounts/pull/30 using symlinks
- [x] track efficient file layout for lookup https://github.com/owncloud/ocis-accounts/issues/2
- [ ] Demo Users (einstein, marie, feynmann) should be provided by accouts service

## ocis-proxy steps (order is important) @refs @IljaN 
- [ ] 1. Middleware for exchanging sub@iss and map them to UUIDs
  - use in proxy: [[Spec]: Expose Account UUID proxy#35](https://github.com/owncloud/ocis-proxy/issues/35) @refs @IljaN 
    - PR [Retrieve Account UUID From User Claims proxy#36
](https://github.com/owncloud/ocis-proxy/pull/36) @refs @IljaN 
  - do **not** autoprovision users. They are explicitly provsioned later or during migration.
  - [x] clarify if middlewares can depend on each other or how they can wrap each other
    - order is important, we could create a middleware that ensures the order of multiple middlewares, like oidc auth, then account lookup: https://medium.com/@chrisgregory_83433/chaining-middleware-in-go-918cfbc5644d
    - nice diagrams on middleware order: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1#middleware-order and a table explcaining the order of middlewares: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1#built-in-middleware
    - **middlewares do in fact rely on each other**
  - [x] store uuid in context @refs @IljaN 
- [ ] 2. check if oc10 endpoint is configured @refs @IljaN 
  - check if user exists in oc10 (because user does not exist in the accounts service)
    - if user exists forward to oc10
  - else create account in ocis and forward to ocis
- [ ] 3. Mint internal token using reva token: @refs @IljaN 
  - like in [ocis-migrations](https://github.com/owncloud/ocis-migration/blob/master/pkg/command/import.go#L77-L99)
  - currently using a shared secret, can be changed later

## ocis-pkg
- middleware for authenticating the requests using a jwt token, similar to the reva `x-access-token`

## ocis-settings Tasks @kulmann 
- settings requests is a seperate requestst that follows tho normal request flow (uses ocis-proxy to authenticate and authorize the user)
- [ ] unmint token from `x-access-token` header using shared secret, see [code reference](https://github.com/cs3org/reva/blob/master/internal/grpc/interceptors/auth/auth.go#L98-L103), see [issue](https://github.com/owncloud/ocis-settings/issues/12)
- [x] use `me` in URLs as placeholder for logged in uuid

# Other
- [ ] CRUD API for Users in accounts service
  - [ ] extend query capabilities: https://github.com/owncloud/ocis-accounts/issues/2
- [ ] Create Frontend for accounts service
    - List Users (MVP)
    - Deactivate / Delete (optional)
 

## Estimation
- Effort: H
- Complexity: H

**Comment by butonic** [comment]
next steps
# ocis-accounts
- update api with graph api properties (onpremis*) to sync
- persist userts on disk using json marshaling of tho go struct
- implement query using bleve (use code from experimental glauth implementation)
