### ISSUE TITLE
ocis Accounts technical debt

### ISSUE THREAD

**Issue by micbar** [owncloud/product#86]
## Tickets
- [x] auto provision new users on login https://github.com/owncloud/ocis-proxy/issues/55 
- [x] respect the disabled flag https://github.com/owncloud/ocis-proxy/issues/53 
- [x] enable accounts by default https://github.com/owncloud/ocis-accounts/issues/43 
- [x] Pass the correct logger https://github.com/owncloud/ocis-accounts/issues/41
 - [x] Add error message to responses https://github.com/owncloud/ocis-accounts/issues/11
 - [x] do not send create home request if user has not yet been migrated https://github.com/owncloud/ocis-proxy/issues/52
- [ ] Initial Release https://github.com/owncloud/ocis-graph/issues/7

- [ ] Detect changes on th json files https://github.com/owncloud/ocis-accounts/issues/42

## To be designed
- [ ] LDAP sync https://github.com/owncloud/ocis-accounts/issues/45
- [ ] Guest accounts https://github.com/owncloud/ocis-accounts/issues/46
- [ ] Fetch roles from the settings service https://github.com/owncloud/ocis-proxy/issues/56

Commitment Sprint 13: Do 4 items
Commitment Sprint 14: Do the next 3 items

Closing now: Follow up tickets are present

**Comment by micbar** [comment]
Cool: Sprint Goal achieved.
Next Items will be planned.
